# Gun Ammo Slot Message
message.gunInfo:
  - "§b§l< %gun% >§r"
  - "§fAmmo: §d%ammo%§r"
# Gun Cooldown Message
message.cooldown: "Cooldown: %cooldown%"
# Gun Item Name & Lore Message
message.gunName: "§d< §f%gun% §d>§r"
message.gunLore:
  - "Info Of: %gun%"
  - "Damage: %damage%"
  - "Ammo: %ammo%"
  - "Scope: %scope%"
  - "Reload cool: %cooldown%"
  - "Distance: %distance%"
  - "Can Pass Walls: %passwall%"